package com.shop.ShopBot.constant;

public enum Trigger {
    UNDEFINED,
    USERNAME,
    NEW_PRODUCT_IMAGE,
    NEW_PRODUCT_NAME,
    NEW_PRODUCT_DESCRIPTION,
    NEW_PRODUCT_PRICE,
    NEW_PRODUCT_ITEMS,
    NEW_PRODUCT_INSTRUCTION,
    EDIT_PRODUCT_IMAGE,
    EDIT_PRODUCT_NAME,
    EDIT_PRODUCT_DESCRIPTION,
    EDIT_PRODUCT_PRICE,
    EDIT_PRODUCT_ITEMS,
    EDIT_PRODUCT_INSTRUCTION
}
