CREATE TABLE IF NOT EXISTS product_image (id SERIAL, image BYTEA, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS dispute_message (id SERIAL, message TEXT, sender CHARACTER VARYING(255), receiver CHARACTER VARYING(255), channel_id BIGINT, date TIMESTAMP(6) WITHOUT TIME ZONE, PRIMARY KEY (id));
